const BUY_POKEMON = "BUY_POKEMON";
const RETURN_POKEMON = "RETURN_POKEMON";
const FETCH_POKEMON_LOADING = "FETCH_POKEMON_LOADING";
const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";

export {
    BUY_POKEMON,
    RETURN_POKEMON,
    FETCH_POKEMON_LOADING,
    FETCH_POKEMON_SUCCESS,
    FETCH_POKEMON_FAILURE,
};
